#!/usr/bin/env python3
"""Generate one shared PNG atlas and vector metadata from the editable artwork.

Authoring needs QtSvg; the Orange Pi runtime only needs its PNG decoder.
"""
import json
from pathlib import Path
from PySide6.QtCore import QByteArray,QRectF
from PySide6.QtGui import QGuiApplication,QImage,QPainter
from PySide6.QtSvg import QSvgRenderer

ROOT=Path(__file__).resolve().parents[1]
art=json.loads((ROOT/'design/icon-source.json').read_text())
theme=json.loads((ROOT/'tools/blueprint/theme.planned.json').read_text())
colors=set()
def collect(value):
    if isinstance(value,str) and value.startswith('#') and len(value)==7:colors.add(value.upper())
    elif isinstance(value,dict):
        for child in value.values():collect(child)
    elif isinstance(value,list):
        for child in value:collect(child)
collect(theme);colors=sorted(colors|{'#1D1D1F','#FFFFFF'})
names=list(art['paths']);tile=48;columns=25
app=QGuiApplication.instance() or QGuiApplication([])
canvas=QImage(columns*tile,((len(names)*len(colors)+columns-1)//columns)*tile,QImage.Format.Format_ARGB32_Premultiplied);canvas.fill(0)
painter=QPainter(canvas)
for color_index,color in enumerate(colors):
    for name_index,name in enumerate(names):
        cell=color_index*len(names)+name_index
        paths=' '.join(art['paths'][name])
        svg=f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><g transform="translate({art["inset"]} {art["inset"]}) scale({art["scale"]})" fill="none" stroke="{color}" stroke-width="{art["strokeWidth"]}" stroke-linecap="round" stroke-linejoin="round"><path d="{paths}"/></g></svg>'
        renderer=QSvgRenderer(QByteArray(svg.encode()));assert renderer.isValid(),name
        renderer.render(painter,QRectF((cell%columns)*tile,(cell//columns)*tile,tile,tile))
painter.end();assert canvas.save(str(ROOT/'bundle/qml/icon-atlas.png'))
out='.pragma library\n// Generated by tools/generate_icons.py; edit design/icon-source.json.\n'
for key,value in [('paths',art['paths']),('aliases',art['aliases']),('names',names),('colors',colors),('tile',tile),('columns',columns)]:out+='var '+key+' = '+json.dumps(value,ensure_ascii=False,separators=(',',':'))+';\n'
out+='''
function colorIndex(value) {
    var rgb=String(value).toUpperCase();
    var exact=colors.indexOf(rgb);
    if (exact>=0) return exact;
    var target=parseInt(rgb.slice(-6),16),best=0,distance=Infinity;
    for (var i=0;i<colors.length;i++) {
        var candidate=parseInt(colors[i].slice(1),16);
        var dr=((target>>16)&255)-((candidate>>16)&255),dg=((target>>8)&255)-((candidate>>8)&255),db=(target&255)-(candidate&255);
        var d=dr*dr+dg*dg+db*db;
        if (d<distance) { best=i;distance=d; }
    }
    return best;
}
function cell(symbol,color) { return colorIndex(color)*names.length+Math.max(0,names.indexOf(symbol)); }
'''
(ROOT/'bundle/qml/IconPaths.js').write_text(out)
print(json.dumps({'glyphs':len(names),'colors':len(colors),'sharedAtlas':[canvas.width(),canvas.height()]}))
