#!/usr/bin/env python3
"""Regenerate distributed editor schema and QML-only fallback from the resolver."""
import json,sys
from pathlib import Path
root=Path(__file__).resolve().parents[1]/'dashboard';sys.path.insert(0,str(root))
from theme_core import ThemeCatalog
catalog=ThemeCatalog(root=root)
base=catalog.resolve('base',motion_mode='off');night=catalog.resolve('base',variant='night',motion_mode='off')
for snapshot in (base,night):
    snapshot['revision']=0
    for role in ('uiFamily','numbersFamily','displayFamily'): snapshot['tokens']['typography.'+role]='DejaVu Sans'
compact=lambda value:json.dumps(value,ensure_ascii=False,separators=(',',':'))
(root/'themes/FallbackAppearance.js').write_text('.pragma library\n// Generated by scripts/generate-theme-contract.py; no runtime JSON dependency.\nvar base = '+compact(base)+'\nvar nightPalette = '+compact({k:v for k,v in night['tokens'].items() if v!=base['tokens'][k]})+'\nfunction make(night) {\n    var result = JSON.parse(JSON.stringify(base))\n    if (night) Object.assign(result.tokens,nightPalette)\n    result.variant = night ? "night" : "day"\n    return result\n}\n')
schema=json.loads((root/'themes/theme-pack.schema.json').read_text());props=schema['properties']
props['name'].update(minLength=1);props['version'].update(pattern=r'^\d+\.\d+\.\d+$');props['extends'].update(pattern=r'^[a-z][a-z0-9_.-]{0,63}$')
tokens={}
for path,spec in catalog.contract.items():
    row={'type':{'color':'string','string':'string','real':'number','int':'integer','bool':'boolean'}[spec['type']],'default':spec['default']}
    if spec['type']=='color':row['pattern']=r'^#[0-9a-fA-F]{6}$'
    if spec['type']=='string':row['maxLength']=120
    for field in ('minimum','maximum'):
        if field in spec:row[field]=spec[field]
    tokens[path]=row
props['tokens']={'type':'object','properties':tokens,'additionalProperties':False}
props['palettes']={'type':'object','properties':{v:{'$ref':'#/properties/tokens'} for v in ('day','night')},'additionalProperties':False}
props['presentations']={'type':'object','additionalProperties':{'type':'string','pattern':r'^[a-z][a-z0-9_.-]{0,63}$'}}
props['motion']={'type':'object','additionalProperties':{'type':'object','required':['recipe','durationMs','distancePx','easing'],'properties':{'recipe':{'type':'string'},'durationMs':{'type':'number','minimum':0,'maximum':600},'distancePx':{'type':'number','minimum':0,'maximum':80},'easing':{'enum':['linear','outCubic','outQuad','inOutQuad']}}}}
props['scene']={'type':'object','properties':{'enabled':{'type':'boolean'},'renderer':{'type':'string'}}}
props['assets']={'type':'array','maxItems':64,'items':{'type':'object','required':['id','type','path'],'properties':{'id':{'type':'string','pattern':r'^[a-z][a-z0-9_.-]{0,63}$'},'type':{'enum':['font','image','data']},'path':{'type':'string','minLength':1},'sha256':{'type':'string','pattern':r'^[0-9a-f]{64}$'}}}}
(root/'themes/theme-pack.schema.json').write_text(json.dumps(schema,ensure_ascii=False,indent=2)+'\n')
